name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3  # This action checks out the repository so that we can access the code

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # This sets up Docker Buildx to enable advanced features, like multi-platform support

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2  # This authenticates the workflow to DockerHub using credentials stored in GitHub secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub username (stored securely in GitHub Secrets)
          password: ${{ secrets.DOCKER_PASSWORD }}  # DockerHub password or access token (stored securely in GitHub Secrets)

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }} .  # Build the image and tag it with the commit SHA (unique to each commit)

      # Step 5: Push the Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }}  # Push the built image to DockerHub with the unique commit tag
